// generated by `sysml rustgen` -- DO NOT EDIT
//
// Definitions of the model become structs and enums; ports bound to
// existing Rust APIs become generic parameters, `perform`ed actions
// methods, and state definitions state machines. What the model
// leaves abstract becomes a trait for you to implement -- alongside
// this file, not in it.
//
// An expression is spelled the way the model spells it, and a
// signature carries the parameters the model declares, so the lints
// that ask for a different spelling have nothing to say about a file
// nobody edits. What the model declares is written whether or not
// the caller reaches for it, which is the other thing a lint would
// otherwise ask about.
// On one line because that is where `rustfmt` puts it, and a
// generated file a reader never edits is still a file they run
// `cargo fmt` over: written the other way, the first thing this
// generator emits is the first thing that comes back as a diff.
#![allow(dead_code, clippy::manual_range_contains, clippy::too_many_arguments)]

/// What runs on the board.
/// SysML: `part def BlinkApp`
pub struct BlinkApp<Board: crate::hal::Gpio> {
    /// SysML: `port board : Gpio`
    pub board: Board,
    pub pin: u8,
    pub half_period_millis: u16,
}

impl<Board: crate::hal::Gpio + Default> Default for BlinkApp<Board> {
    fn default() -> Self {
        Self {
            board: Default::default(),
            pin: 13,
            half_period_millis: 500,
        }
    }
}

impl<Board: crate::hal::Gpio> BlinkApp<Board> {
    /// SysML: `perform action light : SetPin` -> `crate::hal::Gpio::set_pin`
    pub fn light(&mut self, pin: u8, high: bool) {
        self.board.set_pin(pin, high)
    }

    /// SysML: `perform action wait : Wait` -> `crate::hal::Gpio::wait_millis`
    pub fn wait(&mut self, millis: u16) {
        self.board.wait_millis(millis)
    }

    /// SysML: `perform action since : Uptime` -> `crate::hal::Gpio::uptime_millis`
    pub fn since(&self) -> u16 {
        self.board.uptime_millis()
    }
}

/// How long the current half-period has run.
/// SysML: `calc def Elapsed`
pub fn elapsed(now: u16, started_at: u16) -> u16 {
    now - started_at
}

/// Two states, and the LED follows which one is current. The
/// half-period is not in here: when a half-period has passed
/// is the loop's business, and saying so twice is how the two
/// come to disagree.
/// SysML: `state def Blinking` -- the states
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BlinkingState {
    Dark,
    Lit,
}

impl BlinkingState {
    /// The first state the definition declares.
    #[must_use]
    pub fn initial() -> Self {
        BlinkingState::Dark
    }
}

/// What `BlinkingState::step` reacts to.
pub enum BlinkingEvent {
    DarkToLit(Tick),
    LitToDark(Tick),
}

/// The machine's open decisions; every hook has a default.
#[allow(unused_variables)]
pub trait BlinkingHooks {
    fn on_entry_dark(&mut self) {}
    fn on_exit_dark(&mut self) {}
    fn on_entry_lit(&mut self) {}
    fn on_exit_lit(&mut self) {}
}

impl BlinkingState {
    /// One step of the machine: the transition table, guards
    /// first, exit-effect-entry in order.
    #[must_use]
    pub fn step(self, event: &BlinkingEvent, hooks: &mut impl BlinkingHooks) -> Self {
        match (self, event) {
            (BlinkingState::Dark, BlinkingEvent::DarkToLit(_)) => {
                hooks.on_exit_dark();
                hooks.on_entry_lit();
                BlinkingState::Lit
            }
            (BlinkingState::Lit, BlinkingEvent::LitToDark(_)) => {
                hooks.on_exit_lit();
                hooks.on_entry_dark();
                BlinkingState::Dark
            }
            (state, _) => state,
        }
    }
}

/// A half-period has passed; how long it took is the payload.
/// SysML: `part def Tick`
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Tick {
    pub elapsed: u16,
}

/// An Arduino-compatible board with the sketch on it.
/// SysML: `part def BlinkingBoard`
// not generated: `indication` -- SatisfyRequirementUsage not generated
// not generated: `ledPin` -- SatisfyRequirementUsage not generated
// not generated: `logicLevel` -- SatisfyRequirementUsage not generated
// not generated: `room` -- SatisfyRequirementUsage not generated
// not generated: `onBoardLed` -- SatisfyRequirementUsage not generated
// not generated: `period` -- SatisfyRequirementUsage not generated
// not generated: `duty` -- SatisfyRequirementUsage not generated
pub struct BlinkingBoard<AppBoard: crate::hal::Gpio> {
    pub app: BlinkApp<AppBoard>,
    pub status_led_pin: i64,
}

impl<AppBoard: crate::hal::Gpio + Default> Default for BlinkingBoard<AppBoard> {
    fn default() -> Self {
        Self {
            app: Default::default(),
            status_led_pin: 13,
        }
    }
}

/// The model's requirements: one test per requirement, running
/// the verification the model names for it, or ignored and
/// saying so where it names none.
#[cfg(test)]
mod requirements {
    /// SysML: `requirement def VisibleIndication`
    /// The board shall show, without instruments, that it is running.
    /// Satisfied by `statusLed`.
    /// Verified by `VerifyVisibleIndication`.
    #[test]
    fn visible_indication() {
        crate::verification::visible_indication();
    }

    /// SysML: `requirement def LedOnTheSketchesPin`
    /// The status LED shall sit on the pin the sketch writes to. This
    /// is the one requirement that is about neither side alone: the
    /// board decides where the LED is, the sketch decides where it
    /// writes, and the two are only the same by agreement.
    /// Satisfied by `statusLed`.
    #[test]
    #[ignore = "verification not written yet"]
    fn led_on_the_sketches_pin() {}

    /// SysML: `requirement def FiveVoltLogic`
    /// The microcontroller shall drive 5 V logic. A 3.3 V board takes
    /// the same sketch and lights the same LED more dimly, which is
    /// why this is written down rather than assumed from the fact
    /// that it works.
    /// Satisfied by `mcu`.
    #[test]
    #[ignore = "verification not written yet"]
    fn five_volt_logic() {}

    /// SysML: `requirement def RoomForTheSketch`
    /// The flash shall hold the sketch, with the bootloader still in it.
    /// Satisfied by `mcu`.
    #[test]
    #[ignore = "verification not written yet"]
    fn room_for_the_sketch() {}

    /// SysML: `requirement def OnBoardLedOnly`
    /// The indication shall use the LED already on the board, so that
    /// a bare board with nothing wired to it still shows life.
    /// Satisfied by `app`.
    /// Verified by `VerifyOnBoardLedOnly`.
    #[test]
    fn on_board_led_only() {
        crate::verification::on_board_led_only();
    }

    /// SysML: `requirement def PerceptiblePeriod`
    /// A half-period between a tenth of a second and two seconds:
    /// faster reads as a flicker, slower as a fault.
    /// Satisfied by `app`.
    /// Verified by `VerifyPerceptiblePeriod`.
    #[test]
    fn perceptible_period() {
        crate::verification::perceptible_period(100, 2000);
    }

    /// SysML: `requirement def EqualDutyCycle`
    /// Lit and dark shall last the same, so the blink reads as even.
    /// This one carries no constraint on purpose: it is a property of
    /// the state machine rather than of any number, and the model has
    /// no two numbers to compare. What answers for it is a run of the
    /// machine rather than an inspection of it, which is what
    /// `T.4` in `verification.sysml` does.
    /// Satisfied by `app`.
    /// Verified by `VerifyEqualDutyCycle`.
    #[test]
    fn equal_duty_cycle() {
        crate::verification::equal_duty_cycle();
    }

    /// SysML: `requirement blinkingBoardSpecification`
    /// What a compatible board plus this sketch has to be.
    #[test]
    #[ignore = "verification not written yet"]
    fn blinking_board_specification() {}
}
