//! Rust from a resolved SysML model.
//!
//! Two kinds of thing come out of one pass over the model:
//!
//! **Data and structure.** A `part def`, `item def`, `attribute def` or
//! `port def` becomes a struct: attributes and composed parts become
//! fields (multiplicities as containers -- `[*]` a `Vec`, `[0..1]` an
//! `Option`, `[n]` an array), inherited features are flattened in along
//! the reified specializations with redefinitions shadowing what they
//! redefine, and a composition cycle is broken with a `Box` at the edge
//! that closes it. Declared values become a `Default` implementation
//! where every field has one. An `enum def` -- and a variation with
//! `variant` members -- becomes an enum. An `abstract` definition
//! contributes its features to its subtypes but gets no struct of its
//! own.
//!
//! **Calculations.** A `calc def` becomes a function over its `in`
//! parameters and a `calc` usage of a struct a method over its fields.
//! Result expressions in the simple subset -- literals, references,
//! arithmetic, comparisons, logic, `if c ? a else b` -- translate as
//! written (numeric literals keep their spelling, so mixed-type
//! arithmetic surfaces as a Rust type error, not a coercion); anything
//! richer keeps its SysML text behind a `todo!`. An `abstract calc def`
//! declares no formula at all, so it becomes a trait with one method
//! and no default body: what the model leaves open the compiler asks
//! for, rather than a `todo!` waiting to be reached. The same translation
//! gives state-machine guards over their event payload a real default
//! body, and closed expressions (`= 2.0 * 3.0`) their place in
//! `Default`.
//!
//! **Behaviour against existing APIs.** A port typed by a `port def`
//! carrying a `@rust { ... }` binding (what `sysml-import-api` writes)
//! becomes a generic parameter bound to the real Rust trait, and each
//! `perform`ed bound action becomes a method delegating through that
//! port, with the API's own signature: `async`, `Result` and the
//! receiver the binding states. A `state def` becomes a state machine:
//! an enum of states, an enum of the events its transitions accept, a
//! hooks trait carrying guards (their SysML text in the docs), effects
//! and entry/exit notifications, and a `step` function walking the
//! transition table.
//!
//! What has no generated shape is written into the output as a comment
//! rather than dropped. The output is deterministic -- declaration order
//! in, declaration order out -- and intended to be committed next to the
//! model; regenerating and diffing is the drift check.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use sysml_model::{ElementId, ElementKind, Model, Value};

mod expr;
use expr::translate;

/// What stops code generation outright (a model this generator cannot
/// write faithfully); everything smaller is a comment in the output.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RustgenError {
    /// A performed action's binding names no port of the part.
    NoPortForAction {
        part: String,
        action: String,
        path: String,
    },
}

impl std::fmt::Display for RustgenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RustgenError::NoPortForAction { part, action, path } => write!(
                f,
                "`{part}` performs `{action}` bound to `{path}`, but no port of the part \
                 provides that API"
            ),
        }
    }
}

impl std::error::Error for RustgenError {}

/// Rust source for the definitions under `roots`.
pub fn generate(model: &Model, roots: &[ElementId]) -> Result<String, RustgenError> {
    let mut out = String::new();
    writeln!(
        out,
        "// generated by `sysml rustgen` -- DO NOT EDIT\n//\n\
         // Definitions of the model become structs and enums; ports bound to\n\
         // existing Rust APIs become generic parameters, `perform`ed actions\n\
         // methods, and state definitions state machines. What the model\n\
         // leaves abstract becomes a trait for you to implement -- alongside\n\
         // this file, not in it."
    )
    .expect("writing to a String cannot fail");

    let generator = Generator::collect(model, roots);
    for &def in &generator.order {
        generator.definition(def, &mut out)?;
    }
    for &(def, kind) in &generator.skipped {
        let name = model.name(def).expect("collected named");
        writeln!(
            out,
            "\n// not generated: `{name}` -- {} has no Rust shape",
            kind.name()
        )
        .expect("writing to a String cannot fail");
    }
    generator.requirements(roots, &mut out);
    Ok(out)
}

/// How one definition will be generated.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Shape {
    Struct,
    Enum,
    Variation,
    StateMachine,
    /// A `calc def` -- or a `constraint def`, which is one returning a
    /// boolean: a function over its `in` parameters.
    Calculation,
    /// An `action def`: a trait, since a behaviour is not something this
    /// generator can write.
    Action,
    /// Abstract: features flatten into subtypes, no item of its own.
    Flattened,
}

struct Generator<'a> {
    model: &'a Model,
    order: Vec<ElementId>,
    /// Definitions this generator has no shape for, in declaration
    /// order, so that the output says so instead of passing over them.
    skipped: Vec<(ElementId, ElementKind)>,
    shapes: HashMap<ElementId, Shape>,
    /// Generated types that can answer `Default::default()`.
    defaultable: HashSet<ElementId>,
    /// Structs whose fields all support `Debug`/`Clone`/`PartialEq`.
    derivable: HashSet<ElementId>,
    /// Composition edges broken with a `Box` to keep structs finite.
    boxed: HashSet<(ElementId, ElementId)>,
    /// Per struct: its generic parameters and what each composed field
    /// passes along, so parts with API ports compose.
    plans: HashMap<ElementId, Plan>,
}

/// The generic signature of one struct and how its fields use it.
#[derive(Default)]
struct Plan {
    /// Parameters in declaration order: `(name, trait bound)`.
    params: Vec<(String, String)>,
    /// The parameter names each composed usage instantiates its type with.
    arguments: HashMap<ElementId, Vec<String>>,
    /// Fields dropped because a composition cycle would need endless
    /// parameters, by name and note.
    dropped: HashMap<ElementId, String>,
}

impl<'a> Generator<'a> {
    fn collect(model: &'a Model, roots: &[ElementId]) -> Generator<'a> {
        let mut order = Vec::new();
        let mut shapes = HashMap::new();
        let mut skipped: Vec<(ElementId, ElementKind)> = Vec::new();
        for &root in roots {
            for id in model.descendants(root) {
                if model.name(id).is_none() || binding(model, id).is_some() {
                    continue;
                }
                let shape = match model.kind(id) {
                    ElementKind::EnumerationDefinition => Shape::Enum,
                    ElementKind::StateDefinition => Shape::StateMachine,
                    ElementKind::CalculationDefinition => Shape::Calculation,
                    ElementKind::ConstraintDefinition => Shape::Calculation,
                    ElementKind::ActionDefinition => Shape::Action,
                    // an interface or a connection definition is a pair
                    // of ends and whatever they carry -- a struct like
                    // any other definition with features
                    ElementKind::PartDefinition
                    | ElementKind::ItemDefinition
                    | ElementKind::AttributeDefinition
                    | ElementKind::PortDefinition
                    | ElementKind::InterfaceDefinition
                    | ElementKind::ConnectionDefinition => {
                        if model
                            .owned(id)
                            .iter()
                            .any(|&child| model.member_role(child) == Some("variant"))
                        {
                            Shape::Variation
                        } else if model.is_abstract(id) {
                            Shape::Flattened
                        } else {
                            Shape::Struct
                        }
                    }
                    // what has no shape is still said out loud, since
                    // silence reads as "there was nothing here"
                    // a requirement has a shape of its own -- the ignored
                    // test each one becomes -- so it is not skipped. Only
                    // that exact kind: a viewpoint is a requirement by
                    // specialization and gets no test.
                    kind if kind.is_a(ElementKind::Definition)
                        && kind != ElementKind::RequirementDefinition =>
                    {
                        if !skipped.iter().any(|&(seen, _)| seen == id) {
                            skipped.push((id, kind));
                        }
                        continue;
                    }
                    _ => continue,
                };
                if let std::collections::hash_map::Entry::Vacant(slot) = shapes.entry(id) {
                    slot.insert(shape);
                    order.push(id);
                }
            }
        }
        let mut generator = Generator {
            model,
            order,
            skipped,
            shapes,
            defaultable: HashSet::new(),
            derivable: HashSet::new(),
            boxed: HashSet::new(),
            plans: HashMap::new(),
        };
        generator.break_cycles();
        generator.settle_plans();
        generator.settle_defaults();
        generator.settle_derives();
        generator
    }

    /// Depth-first over the composition graph; the edge that would close
    /// a cycle is remembered and later held behind a `Box`.
    fn break_cycles(&mut self) {
        let mut done: HashSet<ElementId> = HashSet::new();
        for &def in &self.order {
            let mut path = Vec::new();
            walk(
                self.model,
                &self.shapes,
                def,
                &mut path,
                &mut done,
                &mut self.boxed,
            );
        }

        fn walk(
            model: &Model,
            shapes: &HashMap<ElementId, Shape>,
            def: ElementId,
            path: &mut Vec<ElementId>,
            done: &mut HashSet<ElementId>,
            boxed: &mut HashSet<(ElementId, ElementId)>,
        ) {
            if done.contains(&def) {
                return;
            }
            path.push(def);
            for &child in model.owned(def) {
                if !matches!(
                    model.kind(child),
                    ElementKind::PartUsage | ElementKind::ItemUsage
                ) {
                    continue;
                }
                // a Vec already breaks the recursion
                if multiplicity(model, child) == Container::Many {
                    continue;
                }
                let Some(target) = type_of(model, child) else {
                    continue;
                };
                if shapes.get(&target) != Some(&Shape::Struct) {
                    continue;
                }
                if path.contains(&target) {
                    boxed.insert((def, target));
                } else {
                    walk(model, shapes, target, path, done, boxed);
                }
            }
            path.pop();
            done.insert(def);
        }
    }

    /// The generic plan of every struct: its own API ports first, then
    /// the parameters every composed generic part needs, renamed after
    /// the field that carries it.
    fn settle_plans(&mut self) {
        // whether a struct's composition subtree touches an API port --
        // a cycle through such a struct cannot be written with finitely
        // many parameters
        let mut reaches: HashMap<ElementId, bool> = HashMap::new();
        let order = self.order.clone();
        for &def in &order {
            self.reaches_ports(def, &mut reaches, &mut HashSet::new());
        }
        for &def in &order {
            if self.shapes[&def] == Shape::Struct {
                let mut visiting = HashSet::new();
                self.plan_of(def, &reaches, &mut visiting);
            }
        }
    }

    fn reaches_ports(
        &self,
        def: ElementId,
        reaches: &mut HashMap<ElementId, bool>,
        visiting: &mut HashSet<ElementId>,
    ) -> bool {
        if let Some(&known) = reaches.get(&def) {
            return known;
        }
        if !visiting.insert(def) {
            return false;
        }
        let mut found = self.has_api_ports(def);
        if !found {
            for field in self.fields(def).unwrap_or_default() {
                if let FieldType::Generated(target) = field.ty {
                    if self.shapes.get(&target) == Some(&Shape::Struct)
                        && self.reaches_ports(target, reaches, visiting)
                    {
                        found = true;
                        break;
                    }
                }
            }
        }
        visiting.remove(&def);
        reaches.insert(def, found);
        found
    }

    fn plan_of(
        &mut self,
        def: ElementId,
        reaches: &HashMap<ElementId, bool>,
        visiting: &mut HashSet<ElementId>,
    ) {
        if self.plans.contains_key(&def) || !visiting.insert(def) {
            return;
        }
        let def_name = self.model.name(def).expect("collected named").to_string();
        let mut plan = Plan::default();
        let mut taken: HashSet<String> = HashSet::new();

        // the struct's own API ports come first
        let mut at = 0;
        for &child in self.model.owned(def) {
            if self.model.kind(child) != ElementKind::PortUsage {
                continue;
            }
            let Some(port) = self.port_of(child) else {
                continue;
            };
            let mut parameter = camel(&port.name);
            if parameter.is_empty() || parameter == def_name || !taken.insert(parameter.clone()) {
                parameter = format!("P{at}");
                taken.insert(parameter.clone());
            }
            plan.params.push((parameter, port.trait_path));
            at += 1;
        }

        // then whatever the composed generic parts need, renamed after
        // the field carrying them
        for field in self.fields(def).unwrap_or_default() {
            let FieldType::Generated(target) = field.ty else {
                continue;
            };
            if self.shapes.get(&target) != Some(&Shape::Struct) {
                continue;
            }
            if visiting.contains(&target) {
                if reaches.get(&target) == Some(&true) {
                    plan.dropped.insert(
                        field.usage,
                        format!(
                            "`{}` -- a composition cycle through API ports has no finite \
                             generic signature",
                            field.name
                        ),
                    );
                }
                continue;
            }
            self.plan_of(target, reaches, visiting);
            let target_params: Vec<(String, String)> = self
                .plans
                .get(&target)
                .map(|plan| plan.params.clone())
                .unwrap_or_default();
            if target_params.is_empty() {
                continue;
            }
            let mut arguments = Vec::new();
            for (theirs, bound) in target_params {
                let mut local = format!("{}{theirs}", camel(&field.name));
                let mut bump = 0;
                while !taken.insert(local.clone()) {
                    bump += 1;
                    local = format!("{}{theirs}{bump}", camel(&field.name));
                }
                arguments.push(local.clone());
                plan.params.push((local, bound));
            }
            plan.arguments.insert(field.usage, arguments);
        }
        visiting.remove(&def);
        self.plans.insert(def, plan);
    }

    /// Which generated types can implement `Default`: enums always (their
    /// first variant), structs when every field can -- computed to a fixed
    /// point because structs compose each other.
    fn settle_defaults(&mut self) {
        for (&def, &shape) in &self.shapes {
            if matches!(shape, Shape::Enum | Shape::Variation) {
                self.defaultable.insert(def);
            }
        }
        loop {
            let mut grew = false;
            for &def in &self.order {
                if self.shapes[&def] != Shape::Struct || self.defaultable.contains(&def) {
                    continue;
                }
                if self.generic(def) {
                    continue;
                }
                // an unbound port is a field of the struct like any
                // other, so `Default` has to be able to start it too
                let ports_fine = self
                    .plain_ports(def)
                    .iter()
                    .all(|field| self.field_defaultable(field));
                if ports_fine
                    && self
                        .fields(def)
                        .is_some_and(|fields| fields.iter().all(|f| self.field_defaultable(f)))
                {
                    self.defaultable.insert(def);
                    grew = true;
                }
            }
            if !grew {
                break;
            }
        }
    }

    /// Which structs can carry `#[derive(Debug, Clone, PartialEq)]`:
    /// those whose fields are scalars or other such structs and enums --
    /// nothing is claimed of external API types.
    fn settle_derives(&mut self) {
        for (&def, &shape) in &self.shapes {
            if matches!(shape, Shape::Enum) {
                self.derivable.insert(def);
            }
        }
        loop {
            let mut grew = false;
            for &def in &self.order {
                if self.shapes[&def] != Shape::Struct || self.derivable.contains(&def) {
                    continue;
                }
                let ports = self
                    .model
                    .owned(def)
                    .iter()
                    .any(|&child| self.model.kind(child) == ElementKind::PortUsage);
                let fields_fine = self.fields(def).is_some_and(|fields| {
                    fields.iter().all(|field| match &field.ty {
                        FieldType::Scalar(_) => true,
                        FieldType::Generated(target) => self.derivable.contains(target),
                        FieldType::External(_) => false,
                    })
                });
                if !ports && !self.generic(def) && fields_fine {
                    self.derivable.insert(def);
                    grew = true;
                }
            }
            if !grew {
                break;
            }
        }
    }

    /// Does this struct carry generic parameters, its own or inherited
    /// from what it composes?
    fn generic(&self, def: ElementId) -> bool {
        self.plans
            .get(&def)
            .is_some_and(|plan| !plan.params.is_empty())
    }

    fn field_defaultable(&self, field: &Field) -> bool {
        if field.default.is_some() {
            return true;
        }
        match field.container {
            // a Vec or an Option is empty by default, whatever it holds
            Container::Many | Container::Optional => true,
            // arrays would need the element to be `Copy` too; not claimed
            Container::Array(_) => false,
            Container::One => match &field.ty {
                FieldType::Scalar(_) => true,
                FieldType::Generated(target) => self.defaultable.contains(target),
                FieldType::External(_) => false,
            },
        }
    }

    /// One definition, whatever its shape.
    fn definition(&self, def: ElementId, out: &mut String) -> Result<(), RustgenError> {
        match self.shapes[&def] {
            Shape::Struct => self.structure(def, out),
            Shape::Enum => {
                self.enumeration(def, out);
                Ok(())
            }
            Shape::Variation => {
                self.variation(def, out);
                Ok(())
            }
            Shape::StateMachine => {
                self.state_machine(def, out);
                Ok(())
            }
            Shape::Calculation => {
                self.calculation(def, out);
                Ok(())
            }
            Shape::Action => {
                self.action(def, out);
                Ok(())
            }
            Shape::Flattened => {
                let name = self.model.name(def).expect("collected named");
                writeln!(
                    out,
                    "\n// `{name}` is abstract: its features flatten into its subtypes."
                )
                .unwrap();
                Ok(())
            }
        }
    }

    /// The flattened data fields of a struct definition: its own
    /// attributes and compositions, then what its specializations hand
    /// down, redefinitions and same names shadowing outward.
    ///
    /// `None` marks a specialization cycle, which cannot flatten.
    fn fields(&self, def: ElementId) -> Option<Vec<Field>> {
        let mut fields = Vec::new();
        let mut taken: HashSet<String> = HashSet::new();
        let mut chain = vec![def];
        let mut visited = HashSet::new();
        while let Some(level) = chain.pop() {
            if !visited.insert(level) {
                return None;
            }
            for &child in self.model.owned(level) {
                if !matches!(
                    self.model.kind(child),
                    ElementKind::AttributeUsage
                        | ElementKind::PartUsage
                        | ElementKind::ItemUsage
                        // the `end`s an interface or connection definition
                        // declares are references, and they are what the
                        // definition is made of
                        | ElementKind::ReferenceUsage
                ) {
                    continue;
                }
                let Some(field) = self.field(def, level, child) else {
                    continue;
                };
                if taken.insert(field.name.clone()) {
                    fields.push(field);
                }
            }
            for &child in self.model.owned(level) {
                if self.model.kind(child) == ElementKind::Subclassification {
                    if let Some(Value::Ref(general)) = self.model.get(child, "superclassifier") {
                        chain.push(*general);
                    }
                }
            }
        }
        Some(fields)
    }

    /// One attribute or composed part as a field, if it has a Rust type.
    fn field(&self, def: ElementId, level: ElementId, usage: ElementId) -> Option<Field> {
        // an unnamed redefinition answers to the name it redefines
        let name = self.model.name(usage).map(str::to_string).or_else(|| {
            self.model
                .name(redefined(self.model, usage)?)
                .map(str::to_string)
        })?;
        let target = type_of(self.model, usage)
            .or_else(|| type_of(self.model, redefined(self.model, usage)?))?;
        let ty = if let Some(bound) = binding(self.model, target) {
            FieldType::External(bound.get("path")?.clone())
        } else if matches!(
            self.shapes.get(&target),
            Some(Shape::Struct | Shape::Enum | Shape::Variation)
        ) {
            // a state machine or an abstract definition is not a value type
            FieldType::Generated(target)
        } else {
            FieldType::Scalar(match self.model.name(target)? {
                "Real" => "f64",
                "Integer" => "i64",
                // `Positive` is a `Natural` the model has ruled zero out
                // of; Rust has no such integer that is also `Default`
                "Natural" | "Positive" => "u64",
                "Boolean" => "bool",
                "String" => "String",
                _ => return None,
            })
        };
        let container = multiplicity(self.model, usage);
        // anything but a Vec keeps the value inline, so a cycle needs a Box
        let boxed = container != Container::Many
            && (self.boxed.contains(&(level, target))
                || matches!(ty, FieldType::Generated(t) if t == def));
        Some(Field {
            name,
            usage,
            ty,
            container,
            boxed,
            default: default_of(self.model, usage),
        })
    }

    /// A `part def` and friends as a struct, its API ports as generics
    /// and its performed bound actions as methods.
    fn structure(&self, def: ElementId, out: &mut String) -> Result<(), RustgenError> {
        let model = self.model;
        let def_name = model.name(def).expect("collected named");
        let mut ports: Vec<Port> = Vec::new();
        let mut plain_ports: Vec<Field> = Vec::new();
        let mut performs = Vec::new();
        let mut calcs = Vec::new();
        let mut asserts = Vec::new();
        let mut states: Vec<(String, String)> = Vec::new();
        let mut notes: Vec<String> = Vec::new();

        let Some(fields) = self.fields(def) else {
            writeln!(
                out,
                "\n// not generated: `{def_name}` -- its specializations form a cycle"
            )
            .unwrap();
            return Ok(());
        };
        for &child in model.owned(def) {
            if model.kind(child).is_a(ElementKind::Relationship)
                || model.kind(child) == ElementKind::MetadataUsage
            {
                continue;
            }
            let Some(child_name) = model.name(child) else {
                continue;
            };
            match model.kind(child) {
                ElementKind::PortUsage => {
                    if let Some(port) = self.port_of(child) {
                        ports.push(port);
                    } else if let Some(field) = self.plain_port(child) {
                        // an unbound port holds the generated struct of
                        // its port definition
                        plain_ports.push(field);
                    } else {
                        notes.push(format!(
                            "port `{child_name}` -- its type is neither bound nor generated"
                        ));
                    }
                }
                ElementKind::PerformActionUsage => performs.push(child),
                ElementKind::CalculationUsage => calcs.push(child),
                ElementKind::AssertConstraintUsage => asserts.push(child),
                ElementKind::StateUsage => match self.state_field(child) {
                    Some(state) => states.push(state),
                    None => notes.push(format!(
                        "state `{child_name}` -- its definition is no generated state machine"
                    )),
                },
                // a nested definition is generated at the top level
                kind if kind.is_a(ElementKind::Definition) => {}
                ElementKind::AttributeUsage
                | ElementKind::PartUsage
                | ElementKind::ItemUsage
                | ElementKind::ReferenceUsage => {
                    if !fields.iter().any(|field| {
                        field.usage == child || Some(field.usage) == redefined(model, child)
                    }) && self.field(def, def, child).is_none()
                    {
                        notes.push(format!("`{child_name}` -- no Rust type for its SysML type"));
                    }
                }
                other => notes.push(format!("`{child_name}` -- {} not generated", other.name())),
            }
        }
        // the plan already named the parameters, own ports first
        let plan = self.plans.get(&def).expect("planned in collect");
        for (port, (parameter, _)) in ports.iter_mut().zip(&plan.params) {
            port.parameter = parameter.clone();
        }
        let mut methods = Vec::new();
        for usage in performs {
            methods.push(self.method(def_name, usage, &ports, &fields)?);
        }
        for usage in calcs {
            match self.calc_method(usage, &fields) {
                Ok(method) => methods.push(method),
                Err(note) => notes.push(note),
            }
        }
        for usage in asserts {
            match self.assertion(usage, &fields) {
                Ok(method) => methods.push(method),
                Err(note) => notes.push(note),
            }
        }

        writeln!(out).unwrap();
        if let Some(doc) = documentation(model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: `part def {def_name}`").unwrap();
        for note in &notes {
            writeln!(out, "// not generated: {note}").unwrap();
        }
        if self.derivable.contains(&def) {
            writeln!(out, "#[derive(Debug, Clone, PartialEq)]").unwrap();
        }
        let generics = plan
            .params
            .iter()
            .map(|(parameter, bound)| format!("{parameter}: {bound}"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "pub struct {def_name}{} {{", angle(&generics)).unwrap();
        for port in &ports {
            writeln!(
                out,
                "    /// SysML: `port {} : {}`",
                port.name, port.type_name
            )
            .unwrap();
            writeln!(out, "    pub {}: {},", ident(&port.name), port.parameter).unwrap();
        }
        for field in plain_ports.iter().chain(&fields) {
            if let Some(dropped) = plan.dropped.get(&field.usage) {
                writeln!(out, "    // not generated: {dropped}").unwrap();
                continue;
            }
            if let Some(doc) = documentation(model, field.usage) {
                doc_comment(&doc, "    ", out);
            }
            writeln!(
                out,
                "    pub {}: {},",
                ident(&field.name),
                self.rust_type(plan, field)
            )
            .unwrap();
        }
        for (state, machine) in &states {
            writeln!(out, "    /// SysML: `state {state}`").unwrap();
            writeln!(out, "    pub {}: {machine},", ident(state)).unwrap();
        }
        writeln!(out, "}}").unwrap();

        // the declared values, where every field has something to start
        // from -- the unbound ports among them, or the struct would name
        // fields its `Default` never fills
        let started = !fields.is_empty() || !plain_ports.is_empty() || !states.is_empty();
        if plan.params.is_empty() && self.defaultable.contains(&def) && started {
            writeln!(out, "\nimpl Default for {def_name} {{").unwrap();
            writeln!(out, "    fn default() -> Self {{").unwrap();
            writeln!(out, "        Self {{").unwrap();
            for field in plain_ports.iter().chain(&fields) {
                writeln!(
                    out,
                    "            {}: {},",
                    ident(&field.name),
                    self.default_value(field)
                )
                .unwrap();
            }
            for (state, machine) in &states {
                writeln!(out, "            {}: {machine}::initial(),", ident(state)).unwrap();
            }
            writeln!(out, "        }}").unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
        }

        if !methods.is_empty() {
            let names = plan
                .params
                .iter()
                .map(|(parameter, _)| parameter.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "\nimpl{} {def_name}{} {{",
                angle(&generics),
                angle(&names)
            )
            .unwrap();
            for (at, method) in methods.iter().enumerate() {
                if at > 0 {
                    writeln!(out).unwrap();
                }
                out.push_str(method);
            }
            writeln!(out, "}}").unwrap();
        }
        Ok(())
    }

    fn rust_type(&self, plan: &Plan, field: &Field) -> String {
        let mut base = match &field.ty {
            FieldType::Scalar(name) => (*name).to_string(),
            FieldType::External(path) => path.clone(),
            FieldType::Generated(target) => {
                let mut name = self
                    .model
                    .name(*target)
                    .expect("collected named")
                    .to_string();
                // a generic part takes the parameters this struct carries
                // on its behalf
                if let Some(arguments) = plan.arguments.get(&field.usage) {
                    name = format!("{name}<{}>", arguments.join(", "));
                }
                name
            }
        };
        if field.boxed {
            base = format!("Box<{base}>");
        }
        contained(base, field.container)
    }

    fn default_value(&self, field: &Field) -> String {
        match (&field.default, &field.container) {
            (Some(rust), Container::One) if !field.boxed => rust.clone(),
            _ => "Default::default()".to_string(),
        }
    }

    /// An `enum def` as an enum, its first value the default.
    fn enumeration(&self, def: ElementId, out: &mut String) {
        let name = self.model.name(def).expect("collected named");
        let mut values = Vec::new();
        let mut notes = Vec::new();
        for &child in self.model.owned(def) {
            let kind = self.model.kind(child);
            let Some(child_name) = self.model.name(child) else {
                continue;
            };
            if kind == ElementKind::EnumerationUsage {
                values.push(child_name);
            } else if !kind.is_a(ElementKind::Relationship) {
                notes.push(format!(
                    "`{child_name}` -- only `enum` values become variants"
                ));
            }
        }
        writeln!(out).unwrap();
        if let Some(doc) = documentation(self.model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: `enum def {name}`").unwrap();
        for note in &notes {
            writeln!(out, "// not generated: {note}").unwrap();
        }
        writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]").unwrap();
        writeln!(out, "pub enum {name} {{").unwrap();
        for value in &values {
            writeln!(out, "    /// SysML: `enum {value}`").unwrap();
            writeln!(out, "    {},", camel(value)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        if let Some(first) = values.first() {
            writeln!(out, "\nimpl Default for {name} {{").unwrap();
            writeln!(out, "    fn default() -> Self {{").unwrap();
            writeln!(out, "        {name}::{}", camel(first)).unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
        }
    }

    /// A variation: one enum variant per `variant`, carrying the
    /// variant's type where it has one.
    fn variation(&self, def: ElementId, out: &mut String) {
        let name = self.model.name(def).expect("collected named");
        writeln!(out).unwrap();
        if let Some(doc) = documentation(self.model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: variation `{name}`").unwrap();
        writeln!(out, "pub enum {name} {{").unwrap();
        for &child in self.model.owned(def) {
            if self.model.member_role(child) != Some("variant") {
                continue;
            }
            let Some(variant) = self.model.name(child) else {
                continue;
            };
            writeln!(out, "    /// SysML: `variant {variant}`").unwrap();
            let payload = type_of(self.model, child)
                .filter(|target| self.shapes.get(target) == Some(&Shape::Struct))
                .and_then(|target| self.model.name(target));
            match payload {
                Some(payload) => writeln!(out, "    {}({payload}),", camel(variant)).unwrap(),
                None => writeln!(out, "    {},", camel(variant)).unwrap(),
            }
        }
        writeln!(out, "}}").unwrap();
    }

    /// A `state def` as a runnable machine: states, events, hooks and a
    /// `step` over the transition table.
    fn state_machine(&self, def: ElementId, out: &mut String) {
        let model = self.model;
        let name = model.name(def).expect("collected named");
        let states: Vec<(ElementId, &str)> = model
            .owned(def)
            .iter()
            .filter_map(|&child| {
                (model.kind(child) == ElementKind::StateUsage)
                    .then(|| model.name(child).map(|n| (child, n)))
                    .flatten()
            })
            .collect();
        let transitions: Vec<Transition> = model
            .owned(def)
            .iter()
            .filter_map(|&child| self.transition(child, &states))
            .collect();

        writeln!(out).unwrap();
        if let Some(doc) = documentation(model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: `state def {name}` -- the states").unwrap();
        writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]").unwrap();
        writeln!(out, "pub enum {name}State {{").unwrap();
        for (_, state) in &states {
            writeln!(out, "    {},", camel(state)).unwrap();
        }
        writeln!(out, "}}").unwrap();
        if let Some((_, first)) = states.first() {
            writeln!(out, "\nimpl {name}State {{").unwrap();
            writeln!(
                out,
                "    /// The first state the definition declares.\n    #[must_use]"
            )
            .unwrap();
            writeln!(out, "    pub fn initial() -> Self {{").unwrap();
            writeln!(out, "        {name}State::{}", camel(first)).unwrap();
            writeln!(out, "    }}").unwrap();
            writeln!(out, "}}").unwrap();
        }

        // one event per transition: the payload it accepts, or a bare
        // signal named after the transition
        writeln!(out, "\n/// What `{name}State::step` reacts to.").unwrap();
        writeln!(out, "pub enum {name}Event {{").unwrap();
        for transition in &transitions {
            match &transition.payload {
                Some((_, ty)) => writeln!(out, "    {}({ty}),", transition.event).unwrap(),
                None => writeln!(out, "    {},", transition.event).unwrap(),
            }
        }
        writeln!(out, "}}").unwrap();

        // guards, effects, and entry/exit notifications, defaulted so an
        // implementation only writes what it cares about
        writeln!(
            out,
            "\n/// The machine's open decisions; every hook has a default."
        )
        .unwrap();
        writeln!(out, "#[allow(unused_variables)]").unwrap();
        writeln!(out, "pub trait {name}Hooks {{").unwrap();
        for transition in &transitions {
            let payload = transition
                .payload
                .as_ref()
                .map(|(param, ty)| format!(", {}: &{ty}", ident(param)))
                .unwrap_or_default();
            if let Some(guard) = &transition.guard {
                // a guard over the event's payload translates into the
                // default body; anything else stays an open decision
                let resolve = |leading: &str| {
                    transition
                        .payload
                        .as_ref()
                        .filter(|(param, _)| param == leading)
                        .map(|(param, _)| ident(param))
                };
                let body = translate(guard, &resolve, &|name| self.callable(name))
                    .filter(|translated| translated.boolean)
                    .map(|translated| translated.rust)
                    .unwrap_or_else(|| "true".to_string());
                writeln!(out, "    /// SysML guard: `[{guard}]`").unwrap();
                writeln!(
                    out,
                    "    fn guard_{}(&self{payload}) -> bool {{\n        {body}\n    }}",
                    ident(&transition.name)
                )
                .unwrap();
            }
            if transition.effect {
                writeln!(out, "    /// SysML effect of `{}`.", transition.name).unwrap();
                writeln!(
                    out,
                    "    fn effect_{}(&mut self{payload}) {{}}",
                    ident(&transition.name)
                )
                .unwrap();
            }
        }
        for (_, state) in &states {
            writeln!(out, "    fn on_entry_{}(&mut self) {{}}", ident(state)).unwrap();
            writeln!(out, "    fn on_exit_{}(&mut self) {{}}", ident(state)).unwrap();
        }
        writeln!(out, "}}").unwrap();

        writeln!(out, "\nimpl {name}State {{").unwrap();
        writeln!(
            out,
            "    /// One step of the machine: the transition table, guards\n    \
             /// first, exit-effect-entry in order."
        )
        .unwrap();
        writeln!(out, "    #[must_use]").unwrap();
        writeln!(
            out,
            "    pub fn step(self, event: &{name}Event, hooks: &mut impl {name}Hooks) -> Self {{"
        )
        .unwrap();
        writeln!(out, "        match (self, event) {{").unwrap();
        for transition in &transitions {
            let pattern = match &transition.payload {
                // only a guard or an effect reads the payload; binding it
                // for an arm that does neither is an unused variable
                Some((param, _)) => format!(
                    "({name}State::{}, {name}Event::{}({}))",
                    camel(&transition.source),
                    transition.event,
                    if transition.guard.is_some() || transition.effect {
                        ident(param)
                    } else {
                        "_".to_string()
                    }
                ),
                None => format!(
                    "({name}State::{}, {name}Event::{})",
                    camel(&transition.source),
                    transition.event
                ),
            };
            let guard = match (&transition.guard, &transition.payload) {
                (Some(_), Some((param, _))) => {
                    format!(
                        " if hooks.guard_{}({})",
                        ident(&transition.name),
                        ident(param)
                    )
                }
                (Some(_), None) => format!(" if hooks.guard_{}()", ident(&transition.name)),
                (None, _) => String::new(),
            };
            writeln!(out, "            {pattern}{guard} => {{").unwrap();
            writeln!(
                out,
                "                hooks.on_exit_{}();",
                ident(&transition.source)
            )
            .unwrap();
            if transition.effect {
                let argument = transition
                    .payload
                    .as_ref()
                    .map(|(param, _)| ident(param))
                    .unwrap_or_default();
                writeln!(
                    out,
                    "                hooks.effect_{}({argument});",
                    ident(&transition.name)
                )
                .unwrap();
            }
            writeln!(
                out,
                "                hooks.on_entry_{}();",
                ident(&transition.target)
            )
            .unwrap();
            writeln!(
                out,
                "                {name}State::{}",
                camel(&transition.target)
            )
            .unwrap();
            writeln!(out, "            }}").unwrap();
        }
        writeln!(out, "            (state, _) => state,").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
    }

    /// One transition of a state machine, when both its ends are states
    /// of the machine.
    fn transition(&self, usage: ElementId, states: &[(ElementId, &str)]) -> Option<Transition> {
        let model = self.model;
        if model.kind(usage) != ElementKind::TransitionUsage {
            return None;
        }
        let name = model.name(usage)?;
        // the two unnamed chaining features are the ends, source first
        let ends: Vec<ElementId> = model
            .owned(usage)
            .iter()
            .filter_map(|&child| {
                if model.kind(child) != ElementKind::Feature {
                    return None;
                }
                match model.get(child, "chainingFeature") {
                    Some(Value::RefList(chain)) => chain.last().copied(),
                    _ => None,
                }
            })
            .collect();
        let state_name = |id: ElementId| {
            states
                .iter()
                .find(|(state, _)| *state == id)
                .map(|(_, n)| (*n).to_string())
        };
        let (&source, &target) = match ends.as_slice() {
            [source, target] => (source, target),
            _ => return None,
        };
        let (source, target) = (state_name(source)?, state_name(target)?);

        // what the transition waits for, and what that carries
        let payload = match model.get(usage, "triggerAction") {
            Some(Value::RefList(triggers)) => triggers.first().and_then(|&accept| {
                let param = model.name(accept)?;
                let ty = type_of(model, accept)?;
                let rust = if let Some(bound) = binding(model, ty) {
                    bound.get("path")?.clone()
                } else if self.shapes.contains_key(&ty) {
                    model.name(ty)?.to_string()
                } else {
                    return None;
                };
                Some((param.to_string(), rust))
            }),
            _ => None,
        };
        let event = match &payload {
            Some(_) => camel(name),
            None => camel(name),
        };
        let guard = match model.get(usage, "guardExpression") {
            Some(Value::RefList(guards)) => guards
                .first()
                .and_then(|&expression| expression_text(model, expression)),
            _ => None,
        };
        let effect = matches!(model.get(usage, "effectAction"), Some(Value::RefList(list)) if !list.is_empty());
        Some(Transition {
            name: name.to_string(),
            source,
            target,
            event,
            payload,
            guard,
            effect,
        })
    }

    /// A `calc def` as a function: `in` parameters become arguments, the
    /// return parameter -- or, failing a declared one, what the result
    /// expression's references agree on -- the return type. A simple
    /// result expression becomes the body; anything richer stays in the
    /// model's own words behind a `todo!`.
    fn calculation(&self, def: ElementId, out: &mut String) {
        let model = self.model;
        let name = model.name(def).expect("collected named");
        let constraint = model.kind(def) == ElementKind::ConstraintDefinition;
        let keyword = if constraint { "constraint" } else { "calc" };
        let mut params: Vec<(String, String)> = Vec::new();
        // a constraint is a boolean expression by definition, whatever
        // its body turns out to say
        let mut declared = constraint.then(|| "bool".to_string());
        let mut clause = None;
        for &child in model.owned(def) {
            if model.member_role(child) == Some("return") {
                match self.parameter_type(child) {
                    Some(ty) => declared = Some(ty),
                    None => {
                        writeln!(
                            out,
                            "\n// not generated: {keyword} def `{name}` -- its return has no Rust type"
                        )
                        .unwrap();
                        return;
                    }
                }
                if let Some(value) = value_clause(model, child) {
                    clause = Some(value);
                }
                continue;
            }
            if model.direction(child) != Some("in") {
                continue;
            }
            let Some(param) = model.name(child) else {
                continue;
            };
            let Some(ty) = self.parameter_type(child) else {
                writeln!(
                    out,
                    "\n// not generated: {keyword} def `{name}` -- parameter `{param}` has no Rust type"
                )
                .unwrap();
                return;
            };
            params.push((param.to_string(), ty));
        }
        if let Some(trailing) = result_clause(model, def) {
            clause = Some(trailing);
        }

        let resolve = |leading: &str| {
            params
                .iter()
                .find(|(param, _)| param == leading)
                .map(|(param, _)| ident(param))
        };
        let translated = match &clause {
            Some(ValueClause::Text(text)) => translate(text, &resolve, &|name| self.callable(name)),
            _ => None,
        };
        // an undeclared return type can still be read off the expression:
        // a comparison is a bool, arithmetic is whatever every referenced
        // parameter is
        let returns = declared.or_else(|| {
            let translated = translated.as_ref()?;
            if translated.boolean {
                return Some("bool".to_string());
            }
            let mut types = translated.references.iter().map(|reference| {
                params
                    .iter()
                    .find(|(param, _)| param == reference)
                    .map(|(_, ty)| ty.clone())
            });
            let first = types.next()??;
            types
                .all(|ty| ty.as_deref() == Some(first.as_str()))
                .then_some(first)
        });
        let Some(returns) = returns else {
            writeln!(
                out,
                "\n// not generated: {keyword} def `{name}` -- its result type is neither declared \
                 nor inferable"
            )
            .unwrap();
            return;
        };
        let arguments = params
            .iter()
            .map(|(param, ty)| format!("{}: {ty}", ident(param)))
            .collect::<Vec<_>>();

        // `abstract` is the model saying it has no formula to give. What
        // Rust has for that is a trait method -- left without a default,
        // so the compiler asks for it -- and not a body that panics when
        // it is finally reached.
        if model.is_abstract(def) {
            let signature = std::iter::once("&self".to_string())
                .chain(arguments)
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out).unwrap();
            if let Some(doc) = documentation(model, def) {
                doc_comment(&doc, "", out);
            }
            writeln!(out, "/// SysML: `abstract {keyword} def {name}`").unwrap();
            writeln!(
                out,
                "/// The model gives no formula; the implementation is yours."
            )
            .unwrap();
            writeln!(out, "pub trait {name} {{").unwrap();
            writeln!(out, "    fn {}({signature}) -> {returns};", ident(name)).unwrap();
            writeln!(out, "}}").unwrap();
            return;
        }

        let (body, unfit) = match (&clause, translated) {
            (_, Some(translated)) => (translated.rust, false),
            (Some(ValueClause::Literal(rust)), None) => (rust.clone(), false),
            (Some(ValueClause::Text(text)), None) => (format!("todo!({text:?})"), true),
            (None, None) => ("todo!()".to_string(), false),
        };

        writeln!(out).unwrap();
        if let Some(doc) = documentation(model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: `{keyword} def {name}`").unwrap();
        if unfit {
            writeln!(
                out,
                "/// The formula is beyond the simple subset; the body is left to write."
            )
            .unwrap();
        }
        if body.starts_with("todo!") {
            writeln!(out, "#[allow(unused_variables)]").unwrap();
        }
        let arguments = arguments.join(", ");
        writeln!(out, "pub fn {}({arguments}) -> {returns} {{", ident(name)).unwrap();
        writeln!(out, "    {body}").unwrap();
        writeln!(out, "}}").unwrap();
    }

    /// A `calc` usage of a struct as a method: its own `in` parameters
    /// as arguments, the struct's fields reachable as `self.field`.
    fn calc_method(&self, usage: ElementId, fields: &[Field]) -> Result<String, String> {
        let model = self.model;
        let name = model.name(usage).expect("named, or it was skipped");

        // typed by a calculation definition and carrying no formula of
        // its own, the usage performs that definition rather than being
        // one: what it says is which of the parameters come off the part
        if let Some(def) = type_of(model, usage) {
            if self.shapes.get(&def) == Some(&Shape::Calculation)
                && result_clause(model, usage).is_none()
                && value_clause(model, usage).is_none()
            {
                return self.calc_delegation(usage, def, fields);
            }
        }

        let Some(returns) = self.parameter_type(usage) else {
            return Err(format!("calc `{name}` -- its result has no Rust type"));
        };
        let mut params: Vec<(String, String)> = Vec::new();
        for &child in model.owned(usage) {
            if model.direction(child) != Some("in") {
                continue;
            }
            let Some(param) = model.name(child) else {
                continue;
            };
            let Some(ty) = self.parameter_type(child) else {
                return Err(format!(
                    "calc `{name}` -- parameter `{param}` has no Rust type"
                ));
            };
            params.push((param.to_string(), ty));
        }

        let resolve = |leading: &str| {
            if let Some((param, _)) = params.iter().find(|(param, _)| param == leading) {
                return Some(ident(param));
            }
            fields
                .iter()
                .find(|field| field.name == leading)
                .map(|field| format!("self.{}", ident(&field.name)))
        };
        let clause = result_clause(model, usage).or_else(|| value_clause(model, usage));
        let translated = match &clause {
            Some(ValueClause::Text(text)) => translate(text, &resolve, &|name| self.callable(name)),
            _ => None,
        };
        let (body, unfit) = match (&clause, translated) {
            (_, Some(translated)) => (translated.rust, false),
            (Some(ValueClause::Literal(rust)), None) => (rust.clone(), false),
            (Some(ValueClause::Text(text)), None) => (format!("todo!({text:?})"), true),
            (None, None) => ("todo!()".to_string(), false),
        };

        let mut method = String::new();
        writeln!(method, "    /// SysML: `calc {name}`").unwrap();
        if unfit {
            writeln!(
                method,
                "    /// The formula is beyond the simple subset; the body is left to write."
            )
            .unwrap();
        }
        if body.starts_with("todo!") {
            writeln!(method, "    #[allow(unused_variables)]").unwrap();
        }
        let arguments = params
            .iter()
            .map(|(param, ty)| format!(", {}: {ty}", ident(param)))
            .collect::<Vec<_>>()
            .join("");
        writeln!(
            method,
            "    pub fn {}(&self{arguments}) -> {returns} {{",
            ident(name)
        )
        .unwrap();
        writeln!(method, "        {body}").unwrap();
        writeln!(method, "    }}").unwrap();
        Ok(method)
    }

    /// A `state` usage of a part: the state its machine is in, as the
    /// generated enum, under the name the model gave the usage.
    fn state_field(&self, usage: ElementId) -> Option<(String, String)> {
        let def = type_of(self.model, usage)?;
        if self.shapes.get(&def) != Some(&Shape::StateMachine) {
            return None;
        }
        let name = self.model.name(usage)?.to_string();
        Some((name, format!("{}State", self.model.name(def)?)))
    }

    /// An `assert constraint` usage as the check it stands for. The model
    /// claims the constraint holds; nothing in Rust can hold anyone to
    /// that, so what is generated is the means of asking.
    fn assertion(&self, usage: ElementId, fields: &[Field]) -> Result<String, String> {
        let model = self.model;
        let name = model.name(usage).expect("named, or it was skipped");
        let Some(def) = type_of(model, usage) else {
            return Err(format!("assert `{name}` -- its constraint did not resolve"));
        };
        if self.shapes.get(&def) != Some(&Shape::Calculation) {
            return Err(format!(
                "assert `{name}` -- `{}` is no generated constraint",
                model.name(def).unwrap_or("?")
            ));
        }
        let performer = model.is_abstract(def);
        self.delegation(usage, def, fields, "assert", "bool", performer, "&")
    }

    /// How the model says a behaviour is put together: the subactions it
    /// is composed of, the order it puts them in, and what flows between
    /// them. None of it becomes code; all of it is what the code has to
    /// do.
    fn decomposition(&self, def: ElementId) -> Vec<String> {
        let model = self.model;
        let mut steps = Vec::new();
        let mut subactions = Vec::new();
        for &child in model.owned(def) {
            match model.kind(child) {
                ElementKind::ActionUsage | ElementKind::PerformActionUsage => {
                    if let Some(name) = model.name(child) {
                        let of = type_of(model, child)
                            .and_then(|ty| model.name(ty))
                            .map(|ty| format!(" : {ty}"))
                            .unwrap_or_default();
                        subactions.push(format!("`{name}{of}`"));
                    }
                }
                kind if kind.is_a(ElementKind::SuccessionAsUsage) => {
                    if let Some(order) = self.ends_of(child) {
                        steps.push(format!("then: {order}"));
                    }
                }
                kind if kind.is_a(ElementKind::FlowUsage) => {
                    if let Some(order) = self.ends_of(child) {
                        steps.push(format!("flow: {order}"));
                    }
                }
                _ => {}
            }
        }
        let mut out = Vec::new();
        if !subactions.is_empty() {
            out.push(format!("Made of {}.", subactions.join(", ")));
        }
        out.extend(steps);
        out
    }

    /// The two ends of a succession or a flow, as the model resolved
    /// them -- `relatedFeature` is where the semantics pass records what
    /// the operands of `first ... then ...` and `flow ... to ...` point
    /// at.
    fn ends_of(&self, usage: ElementId) -> Option<String> {
        let ends = self.model.related_feature(usage);
        let named: Vec<&str> = ends
            .iter()
            .filter_map(|&end| self.model.name(end))
            .collect();
        (named.len() == 2).then(|| format!("`{}` -> `{}`", named[0], named[1]))
    }

    /// What an action definition's `out` parameters make of its result:
    /// nothing, the one type, or a tuple of them.
    fn action_result(&self, def: ElementId) -> Option<String> {
        let model = self.model;
        let mut outputs = Vec::new();
        for &child in model.owned(def) {
            if model.direction(child) != Some("out") {
                continue;
            }
            outputs.push(self.parameter_type(child)?);
        }
        Some(match outputs.len() {
            0 => "()".to_string(),
            1 => outputs.join(""),
            _ => format!("({})", outputs.join(", ")),
        })
    }

    /// An `action def` as a trait with one method: `in` parameters become
    /// its arguments and `out` parameters its result -- a tuple where
    /// there are several. A behaviour assembled from subactions, flows
    /// and successions is not something this generator can write, so it
    /// asks for it the way it asks for an abstract calculation.
    fn action(&self, def: ElementId, out: &mut String) {
        let model = self.model;
        let name = model.name(def).expect("collected named");
        let mut inputs: Vec<String> = Vec::new();
        for &child in model.owned(def) {
            if model.direction(child) != Some("in") {
                continue;
            }
            let Some(param) = model.name(child) else {
                continue;
            };
            let Some(ty) = self.parameter_type(child) else {
                writeln!(
                    out,
                    "\n// not generated: action def `{name}` -- parameter `{param}` has no \
                     Rust type"
                )
                .unwrap();
                return;
            };
            inputs.push(format!("{}: {ty}", ident(param)));
        }
        let Some(returns) = self.action_result(def) else {
            writeln!(
                out,
                "\n// not generated: action def `{name}` -- a result of it has no Rust type"
            )
            .unwrap();
            return;
        };
        let signature = std::iter::once("&mut self".to_string())
            .chain(inputs)
            .collect::<Vec<_>>()
            .join(", ");

        writeln!(out).unwrap();
        if let Some(doc) = documentation(model, def) {
            doc_comment(&doc, "", out);
        }
        writeln!(out, "/// SysML: `action def {name}`").unwrap();
        writeln!(
            out,
            "/// The model names this behaviour without saying how it runs; \
             the implementation is yours."
        )
        .unwrap();
        // What the model does say is what the behaviour is made of. The
        // generator cannot compile a dataflow into a body, but it can
        // hand the implementor the model's own account of one instead of
        // making them go and read it.
        for step in self.decomposition(def) {
            writeln!(out, "/// {step}").unwrap();
        }
        writeln!(out, "pub trait {name} {{").unwrap();
        writeln!(
            out,
            "    fn {}({signature}){};",
            ident(name),
            returns_clause(&returns)
        )
        .unwrap();
        writeln!(out, "}}").unwrap();
    }

    /// A `calc` usage typed by a calculation definition, as a method that
    /// performs it: the parameters the usage bound are read off the part,
    /// the rest stay arguments of the method, and the calculation itself
    /// is called outright where the definition had a formula, or arrives
    /// as an implementation of the trait an `abstract` one generated.
    fn calc_delegation(
        &self,
        usage: ElementId,
        def: ElementId,
        fields: &[Field],
    ) -> Result<String, String> {
        let model = self.model;
        let name = model.name(usage).expect("named, or it was skipped");
        let def_name = model.name(def).expect("collected named");
        let returns = model
            .owned(def)
            .iter()
            .copied()
            .find(|&child| model.member_role(child) == Some("return"))
            .and_then(|child| self.parameter_type(child));
        let Some(returns) = returns else {
            return Err(format!(
                "calc `{name}` -- the result of `{def_name}` has no Rust type"
            ));
        };
        // an abstract definition generated a trait, so the caller brings
        // the implementation along; a concrete one generated a function
        let performer = model.is_abstract(def);
        self.delegation(usage, def, fields, "calc", &returns, performer, "&")
    }

    /// The body common to every performance of a definition: pair each of
    /// the definition's `in` parameters with what the usage bound it to,
    /// leave the rest for the caller, and write the method around them.
    #[allow(clippy::too_many_arguments)]
    fn delegation(
        &self,
        usage: ElementId,
        def: ElementId,
        fields: &[Field],
        label: &str,
        returns: &str,
        performer: bool,
        provider_ref: &str,
    ) -> Result<String, String> {
        let model = self.model;
        let name = model.name(usage).expect("named, or it was skipped");
        let def_name = model.name(def).expect("collected named");
        let resolve = |leading: &str| {
            fields
                .iter()
                .find(|field| field.name == leading)
                .map(|field| format!("self.{}", ident(&field.name)))
        };

        let mut params: Vec<(String, String)> = Vec::new();
        let mut arguments: Vec<String> = Vec::new();
        for &child in model.owned(def) {
            if model.direction(child) != Some("in") {
                continue;
            }
            let Some(param) = model.name(child) else {
                continue;
            };
            let Some(ty) = self.parameter_type(child) else {
                return Err(format!(
                    "{label} `{name}` -- parameter `{param}` of `{def_name}` has no Rust type"
                ));
            };
            // whatever the usage did not bind, the caller still owes
            let bound = model
                .owned(usage)
                .iter()
                .copied()
                .find(|&sibling| model.name(sibling) == Some(param))
                .and_then(|sibling| value_clause(model, sibling));
            let Some(clause) = bound else {
                arguments.push(ident(param));
                params.push((param.to_string(), ty));
                continue;
            };
            let read = match clause {
                ValueClause::Literal(rust) => rust,
                ValueClause::Text(text) => {
                    match translate(&text, &resolve, &|name| self.callable(name)) {
                        Some(translated) => translated.rust,
                        None => {
                            return Err(format!(
                                "{label} `{name}` -- `{param}` is bound to `{text}`, beyond the \
                             simple subset"
                            ))
                        }
                    }
                }
            };
            let Some(argument) = self.owned_argument(read, &ty, child) else {
                return Err(format!(
                    "{label} `{name}` -- `{param}` is read off the part, and `{ty}` cannot be \
                     cloned into the call"
                ));
            };
            arguments.push(argument);
        }

        let provider = if params.iter().any(|(param, _)| param == "with") {
            "with_"
        } else {
            "with"
        };
        let mut signature = String::from("&self");
        if performer {
            write!(signature, ", {provider}: {provider_ref}impl {def_name}").unwrap();
        }
        for (param, ty) in &params {
            write!(signature, ", {}: {ty}", ident(param)).unwrap();
        }
        let arguments = arguments.join(", ");
        let call = if performer {
            format!("{provider}.{}({arguments})", ident(def_name))
        } else {
            format!("{}({arguments})", ident(def_name))
        };

        let mut method = String::new();
        writeln!(method, "    /// SysML: `{label} {name} : {def_name}`").unwrap();
        writeln!(
            method,
            "    pub fn {}({signature}){} {{",
            ident(name),
            returns_clause(returns)
        )
        .unwrap();
        writeln!(method, "        {call}").unwrap();
        writeln!(method, "    }}").unwrap();
        Ok(method)
    }

    /// A bound argument as something the call can take by value: reading
    /// a field has to clone it, since the method only borrows the part.
    fn owned_argument(&self, read: String, ty: &str, param: ElementId) -> Option<String> {
        let copyable = matches!(ty, "f64" | "i64" | "u64" | "bool");
        let field_read = read.strip_prefix("self.").is_some_and(|rest| {
            rest.chars()
                .all(|ch| ch.is_alphanumeric() || ch == '_' || ch == '#')
        });
        if copyable || !field_read {
            return Some(read);
        }
        let clonable = ty == "String"
            || type_of(self.model, param).is_some_and(|target| self.derivable.contains(&target));
        clonable.then(|| format!("{read}.clone()"))
    }

    /// An unbound port as a plain field of its generated port struct.
    fn plain_port(&self, usage: ElementId) -> Option<Field> {
        let target = type_of(self.model, usage)?;
        if self.shapes.get(&target) != Some(&Shape::Struct) || self.has_api_ports(target) {
            return None;
        }
        Some(Field {
            name: self.model.name(usage)?.to_string(),
            usage,
            ty: FieldType::Generated(target),
            container: multiplicity(self.model, usage),
            boxed: false,
            default: None,
        })
    }

    /// The ports of a definition that hold the generated struct of their
    /// port definition rather than a bound API. They become fields like
    /// any other, so what is asked of a field is asked of them too.
    fn plain_ports(&self, def: ElementId) -> Vec<Field> {
        self.model
            .owned(def)
            .iter()
            .filter(|&&child| self.model.kind(child) == ElementKind::PortUsage)
            .filter_map(|&child| self.plain_port(child))
            .collect()
    }

    /// Does this definition hold ports bound to external APIs -- which
    /// generate as generic parameters, not composable fields?
    fn has_api_ports(&self, def: ElementId) -> bool {
        self.model.owned(def).iter().any(|&child| {
            self.model.kind(child) == ElementKind::PortUsage && self.port_of(child).is_some()
        })
    }

    /// The model's requirements, as ignored test stubs: each names what
    /// the model says satisfies it, and waits for a real verification.
    fn requirements(&self, roots: &[ElementId], out: &mut String) {
        let model = self.model;
        let mut stubs = Vec::new();
        let mut named = HashSet::new();
        for &root in roots {
            for id in model.descendants(root) {
                if !matches!(
                    model.kind(id),
                    ElementKind::RequirementDefinition | ElementKind::RequirementUsage
                ) {
                    continue;
                }
                let Some(name) = model.name(id) else {
                    continue;
                };
                if !named.insert(name.to_string()) {
                    continue;
                }
                // what the model claims satisfies this requirement
                let satisfiers: Vec<String> = model
                    .ids()
                    .filter(|&satisfy| {
                        model
                            .kind(satisfy)
                            .is_a(ElementKind::SatisfyRequirementUsage)
                            && model.get(satisfy, "satisfiedRequirement") == Some(&Value::Ref(id))
                    })
                    .filter_map(|satisfy| match model.get(satisfy, "satisfyingFeature") {
                        Some(Value::Ref(feature)) => model.name(*feature).map(str::to_string),
                        _ => None,
                    })
                    .collect();
                stubs.push((name.to_string(), documentation(model, id), satisfiers));
            }
        }
        if stubs.is_empty() {
            return;
        }
        writeln!(
            out,
            "\n/// The model's requirements: one ignored test per requirement,\n\
             /// waiting for its verification to be written.\n\
             #[cfg(test)]\n\
             mod requirements {{"
        )
        .unwrap();
        for (at, (name, doc, satisfiers)) in stubs.iter().enumerate() {
            if at > 0 {
                writeln!(out).unwrap();
            }
            writeln!(out, "    /// SysML: `requirement def {name}`").unwrap();
            if let Some(doc) = doc {
                doc_comment(doc, "    ", out);
            }
            for satisfier in satisfiers {
                writeln!(out, "    /// Satisfied by `{satisfier}`.").unwrap();
            }
            writeln!(out, "    #[test]").unwrap();
            writeln!(out, "    #[ignore = \"verification not written yet\"]").unwrap();
            writeln!(out, "    fn {}() {{}}", ident(name)).unwrap();
        }
        writeln!(out, "}}").unwrap();
    }

    fn port_of(&self, usage: ElementId) -> Option<Port> {
        let port_def = type_of(self.model, usage)?;
        let bound = binding(self.model, port_def)?;
        let path = bound.get("path")?.clone();
        Some(Port {
            name: self.model.name(usage)?.to_string(),
            type_name: self.model.name(port_def)?.to_string(),
            parameter: String::new(),
            trait_path: path,
        })
    }

    /// One performed API action as a delegating method.
    fn method(
        &self,
        part_name: &str,
        usage: ElementId,
        ports: &[Port],
        fields: &[Field],
    ) -> Result<String, RustgenError> {
        let model = self.model;
        let usage_name = model.name(usage).expect("named, or it was skipped");
        let Some(action) = type_of(model, usage) else {
            return Ok(format!(
                "    // not generated: perform `{usage_name}` -- its action did not resolve\n"
            ));
        };
        let Some(bound) = binding(model, action) else {
            // no binding to delegate through, but the model still named
            // the behaviour: the trait its definition generated is what
            // the part performs it with
            if self.shapes.get(&action) == Some(&Shape::Action) {
                let Some(returns) = self.action_result(action) else {
                    return Ok(format!(
                        "    // not generated: perform `{usage_name}` -- a result of it has no \
                         Rust type\n"
                    ));
                };
                return Ok(
                    match self.delegation(usage, action, fields, "perform", &returns, true, "&mut ")
                    {
                        Ok(method) => method,
                        Err(note) => format!("    // not generated: {note}\n"),
                    },
                );
            }
            return Ok(format!(
                "    // not generated: perform `{usage_name}` -- `{}` carries no `@rust` binding\n",
                model.name(action).unwrap_or("?")
            ));
        };
        let path = bound.get("path").cloned().unwrap_or_default();
        let takes_self = bound.get("takesSelf").map(String::as_str).unwrap_or("");
        if takes_self == "self" {
            return Ok(format!(
                "    // not generated: perform `{usage_name}` -- `{path}` consumes its receiver\n"
            ));
        }
        let provider = ports
            .iter()
            .find(|port| path.starts_with(&format!("{}::", port.trait_path)));
        let Some(provider) = provider else {
            return Err(RustgenError::NoPortForAction {
                part: part_name.to_string(),
                action: usage_name.to_string(),
                path,
            });
        };
        let callee = path.rsplit("::").next().unwrap_or(&path);

        let mut inputs = Vec::new();
        let mut output = None;
        let mut error = None;
        for &parameter in model.owned(action) {
            let Some(direction) = model.direction(parameter) else {
                continue;
            };
            let name = model.name(parameter).unwrap_or("_");
            let Some((base, container)) = self.parameter_shape(parameter) else {
                return Ok(format!(
                    "    // not generated: perform `{usage_name}` -- parameter `{name}` has no Rust type\n"
                ));
            };
            match (direction, name) {
                ("in", _) => inputs.push((ident(name), contained(base, container))),
                // the `Result` around it is what says it may be absent
                ("out", "error") => error = Some(base),
                ("out", _) => output = Some(contained(base, container)),
                _ => {}
            }
        }

        let is_async = bound.get("isAsync").map(String::as_str) == Some("true");
        let fallible = bound.get("isFallible").map(String::as_str) == Some("true");
        let receiver = if takes_self == "&mut self" {
            "&mut self"
        } else {
            "&self"
        };
        let mut signature = format!(
            "    pub {}fn {}({receiver}",
            if is_async { "async " } else { "" },
            ident(usage_name),
        );
        for (name, ty) in &inputs {
            write!(signature, ", {name}: {ty}").unwrap();
        }
        signature.push(')');
        let returned = match (&output, &error) {
            (Some(ok), Some(err)) if fallible => Some(format!("Result<{ok}, {err}>")),
            (Some(ok), _) => Some(ok.clone()),
            (None, Some(err)) if fallible => Some(format!("Result<(), {err}>")),
            _ => None,
        };
        if let Some(returned) = &returned {
            write!(signature, " -> {returned}").unwrap();
        }

        let mut call = format!(
            "self.{}.{callee}({})",
            ident(&provider.name),
            inputs
                .iter()
                .map(|(name, _)| name.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        );
        if is_async {
            call.push_str(".await");
        }

        let mut body = String::new();
        writeln!(
            body,
            "    /// SysML: `perform action {usage_name} : {}` -> `{path}`",
            model.name(action).unwrap_or("?")
        )
        .unwrap();
        writeln!(body, "{signature} {{").unwrap();
        writeln!(body, "        {call}").unwrap();
        writeln!(body, "    }}").unwrap();
        Ok(body)
    }

    /// The Rust type of an action parameter.
    fn parameter_type(&self, usage: ElementId) -> Option<String> {
        let (base, container) = self.parameter_shape(usage)?;
        Some(contained(base, container))
    }

    /// How Rust spells a call to a named calculation: the function its
    /// definition generated, where the definition generated one. An
    /// `abstract` definition became a trait instead, and a trait method
    /// is not callable out of nowhere.
    fn callable(&self, name: &str) -> Option<expr::Callee> {
        let (&target, _) = self.shapes.iter().find(|(&id, &shape)| {
            shape == Shape::Calculation && self.model.name(id) == Some(name)
        })?;
        if self.model.is_abstract(target) {
            return None;
        }
        // in declaration order, which is the order the generated function
        // takes them in, so a call that named its arguments can be put
        // back into it
        let parameters = self
            .model
            .owned(target)
            .iter()
            .filter(|&&child| self.model.direction(child) == Some("in"))
            .filter_map(|&child| self.model.name(child).map(str::to_string))
            .collect();
        Some(expr::Callee {
            function: ident(name),
            parameters,
        })
    }

    /// The Rust type of a parameter and the container its multiplicity
    /// asks for, apart -- the error of a `Result` states its own
    /// optionality by being the error, and must not be wrapped again.
    fn parameter_shape(&self, usage: ElementId) -> Option<(String, Container)> {
        // a parameter bound by a usage -- `in previous = stateVector` --
        // declares no type of its own; it keeps the one it redefines
        let declaring = type_of(self.model, usage)
            .map(|_| usage)
            .or_else(|| redefined(self.model, usage))?;
        let ty = type_of(self.model, declaring)?;
        // a parameter carries its multiplicity the way a field does: a
        // `[1..*]` of something is a `Vec` of it, not one of it
        let container = multiplicity(self.model, declaring);
        if let Some(bound) = binding(self.model, ty) {
            return bound.get("path").cloned().map(|path| (path, container));
        }
        if self.shapes.contains_key(&ty) {
            return self
                .model
                .name(ty)
                .map(|name| (name.to_string(), container));
        }
        let scalar = match self.model.name(ty)? {
            "Real" => "f64",
            "Integer" => "i64",
            "Natural" | "Positive" => "u64",
            "Boolean" => "bool",
            "String" => "String",
            _ => return None,
        };
        Some((scalar.to_string(), container))
    }
}

/// A port of a part, once its type turned out to be a bound API trait.
struct Port {
    name: String,
    type_name: String,
    parameter: String,
    trait_path: String,
}

/// One data field of a generated struct.
struct Field {
    name: String,
    usage: ElementId,
    ty: FieldType,
    container: Container,
    /// The element type sits behind a `Box`, breaking a composition cycle.
    boxed: bool,
    /// The declared `= value`, already rendered as Rust.
    default: Option<String>,
}

enum FieldType {
    Scalar(&'static str),
    Generated(ElementId),
    External(String),
}

/// What a multiplicity wraps the element type in.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Container {
    One,
    Optional,
    Many,
    Array(i64),
}

/// The `= value` clause of a usage: a literal already rendered as Rust,
/// or the SysML text of an expression, still to translate.
enum ValueClause {
    Literal(String),
    Text(String),
}

/// One transition, ready to be written into the table.
struct Transition {
    name: String,
    source: String,
    target: String,
    event: String,
    /// The accepted payload: its parameter name and Rust type.
    payload: Option<(String, String)>,
    /// The guard's SysML text, for the hook's documentation.
    guard: Option<String>,
    effect: bool,
}

/// The declared multiplicity of a usage, as the container it implies.
/// The return clause of a signature -- nothing at all where there is
/// nothing to return, since `-> ()` is noise, and noise clippy objects to.
fn returns_clause(returns: &str) -> String {
    if returns == "()" {
        String::new()
    } else {
        format!(" -> {returns}")
    }
}

/// A type under the container its multiplicity asks for.
fn contained(base: String, container: Container) -> String {
    match container {
        Container::One => base,
        Container::Optional => format!("Option<{base}>"),
        Container::Many => format!("Vec<{base}>"),
        Container::Array(n) => format!("[{base}; {n}]"),
    }
}

fn multiplicity(model: &Model, usage: ElementId) -> Container {
    let Some(Value::Ref(range)) = model.get(usage, "multiplicity") else {
        return Container::One;
    };
    let bound_value = |name: &str| -> Option<BoundKind> {
        let Some(Value::Ref(bound)) = model.get(*range, name) else {
            return None;
        };
        if model.kind(*bound) == ElementKind::LiteralInfinity {
            return Some(BoundKind::Many);
        }
        match model.get(*bound, "value") {
            Some(Value::Int(int)) => Some(BoundKind::Exactly(*int)),
            _ => Some(BoundKind::Unknown),
        }
    };
    match (
        bound_value("bound"),
        bound_value("lowerBound"),
        bound_value("upperBound"),
    ) {
        (Some(BoundKind::Many), _, _) => Container::Many,
        (Some(BoundKind::Exactly(n)), _, _) if n > 0 => Container::Array(n),
        (None, Some(BoundKind::Exactly(0)), Some(BoundKind::Exactly(1))) => Container::Optional,
        (None, Some(_), Some(_)) => Container::Many,
        _ => Container::Many,
    }
}

enum BoundKind {
    Many,
    Exactly(i64),
    Unknown,
}

/// The `= value` a usage declared, as far as Rust can start from it: a
/// literal as itself, a closed simple expression (`2.0 * 3.0`) as
/// written -- an expression over other features has no place in
/// `Default::default()`.
fn default_of(model: &Model, usage: ElementId) -> Option<String> {
    match value_clause(model, usage)? {
        ValueClause::Literal(rust) => Some(rust),
        ValueClause::Text(text) => Some(translate(&text, &|_| None, &|_| None)?.rust),
    }
}

/// The trailing result expression of a calculation body, where one was
/// written -- the last one wins, as the spec has it.
fn result_clause(model: &Model, element: ElementId) -> Option<ValueClause> {
    let mut clause = None;
    for &child in model.owned(element) {
        if model.kind(child) == ElementKind::Expression
            && model.member_role(child) == Some("result")
        {
            if let Some(text) = expression_text(model, child) {
                clause = Some(ValueClause::Text(text));
            }
        }
    }
    clause
}

/// The `= value` clause of a usage, ready for translation.
fn value_clause(model: &Model, usage: ElementId) -> Option<ValueClause> {
    let membership = model
        .owned(usage)
        .iter()
        .copied()
        .find(|&child| model.kind(child) == ElementKind::FeatureValue)?;
    let Some(Value::Ref(expression)) = model.get(membership, "value") else {
        return None;
    };
    let rust = match model.get(*expression, "value") {
        Some(Value::Real(real)) => format!("{real:?}"),
        Some(Value::Int(int)) => format!("{int}"),
        Some(Value::Bool(flag)) => format!("{flag}"),
        Some(Value::String(text)) => format!("{text:?}.to_string()"),
        _ => return expression_text(model, *expression).map(ValueClause::Text),
    };
    Some(ValueClause::Literal(rust))
}

/// The written text of an expression element, off the textual
/// representation the builder keeps for what it does not evaluate.
fn expression_text(model: &Model, expression: ElementId) -> Option<String> {
    model.owned(expression).iter().find_map(|&written| {
        (model.kind(written) == ElementKind::TextualRepresentation)
            .then(|| model.get(written, "body"))
            .flatten()?
            .as_str()
            .map(str::to_string)
    })
}

/// What an unnamed redefining usage redefines, so it can borrow the name.
fn redefined(model: &Model, usage: ElementId) -> Option<ElementId> {
    model.owned(usage).iter().find_map(|&child| {
        (model.kind(child) == ElementKind::Redefinition)
            .then(|| model.redefined_feature(child))
            .flatten()
    })
}

/// The resolved type of a usage, off its reified typing.
fn type_of(model: &Model, usage: ElementId) -> Option<ElementId> {
    model.owned(usage).iter().find_map(|&child| {
        if model.kind(child) != ElementKind::FeatureTyping {
            return None;
        }
        match model.get(child, "type") {
            Some(Value::Ref(target)) => Some(*target),
            _ => None,
        }
    })
}

/// The `@rust { :>> name = value; ... }` pairs of one element, if it
/// carries a binding.
fn binding(model: &Model, element: ElementId) -> Option<HashMap<String, String>> {
    let mut out = HashMap::new();
    for &child in model.owned(element) {
        if model.kind(child) != ElementKind::MetadataUsage {
            continue;
        }
        for &setting in model.owned(child) {
            let redefined = model.owned(setting).iter().copied().find_map(|rel| {
                if model.kind(rel) != ElementKind::Redefinition {
                    return None;
                }
                match model.get(rel, "redefinedFeature") {
                    Some(Value::Ref(target)) => Some(*target),
                    _ => None,
                }
            });
            let value = model.owned(setting).iter().copied().find_map(|part| {
                if model.kind(part) != ElementKind::FeatureValue {
                    return None;
                }
                match model.get(part, "value") {
                    Some(Value::Ref(literal)) => Some(*literal),
                    _ => None,
                }
            });
            let (Some(redefined), Some(value)) = (redefined, value) else {
                continue;
            };
            let Some(name) = model.name(redefined) else {
                continue;
            };
            let rendered = match model.get(value, "value") {
                Some(Value::String(text)) => text.clone(),
                Some(Value::Bool(flag)) => flag.to_string(),
                Some(Value::Int(int)) => int.to_string(),
                _ => continue,
            };
            out.insert(name.to_string(), rendered);
        }
    }
    (!out.is_empty()).then_some(out)
}

/// The element's documentation text, if it has any, laid out as it was
/// written: a `doc /* ... */` spanning several lines keeps its lines, and
/// each of them loses the indentation and the `*` that line it up in the
/// model text -- neither of which belongs in a Rust doc comment.
fn documentation(model: &Model, element: ElementId) -> Option<String> {
    model.owned(element).iter().find_map(|&child| {
        if model.kind(child) != ElementKind::Documentation {
            return None;
        }
        let body = model.get(child, "body")?.as_str()?;
        let lines: Vec<&str> = body
            .lines()
            .map(|line| {
                let line = line.trim_start();
                let line = line.strip_prefix('*').unwrap_or(line);
                // one space after the `*` is the marker's own; any
                // further indentation the writer meant, so it stays
                let line = line.strip_prefix(' ').unwrap_or(line);
                line.trim_end()
            })
            .skip_while(|line| line.is_empty())
            .collect();
        let end = lines.iter().rposition(|line| !line.is_empty())? + 1;
        Some(lines[..end].join("\n"))
    })
}

/// Documentation as Rust doc comments, one line of `///` per line of the
/// original, each behind `indent` so a field's docs sit with the field.
fn doc_comment(doc: &str, indent: &str, out: &mut String) {
    for line in doc.lines() {
        if line.is_empty() {
            writeln!(out, "{indent}///").unwrap();
        } else {
            writeln!(out, "{indent}/// {line}").unwrap();
        }
    }
}

/// `<...>` unless there is nothing to put in it.
fn angle(list: &str) -> String {
    if list.is_empty() {
        String::new()
    } else {
        format!("<{list}>")
    }
}

/// `StockVisibility` -> `stock_visibility`: the case Rust asks of
/// everything but a type, and SysML of nothing.
fn snake(name: &str) -> String {
    let mut out = String::new();
    for (at, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if at > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// `store` -> `Store`, for parameters, variants and event names.
fn camel(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// A SysML name as the Rust name of a field, parameter or method:
/// `spectralRadius` -> `spectral_radius`, since the model's own
/// convention is the one Rust keeps for types; anything Rust cannot
/// spell in an identifier becomes `_`; and a reserved word is taken raw,
/// or suffixed where no raw form exists.
fn ident(name: &str) -> String {
    /// Everything Rust has taken, including what it has only reserved.
    const RESERVED: [&str; 51] = [
        "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "do",
        "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in", "let",
        "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
        "static", "struct", "trait", "true", "try", "type", "typeof", "unsafe", "unsized", "use",
        "virtual", "where", "while", "yield",
        // no raw form exists for these, so they take a suffix instead
        "crate", "self", "Self", "super",
    ];
    /// The keywords `r#` cannot rescue.
    const SUFFIXED: [&str; 4] = ["crate", "self", "Self", "super"];

    // an escaped name may hold anything at all -- `'provide transportation'`
    // is one name in SysML -- and Rust spells identifiers out of a much
    // smaller alphabet
    let name: String = snake(name)
        .chars()
        .map(|ch| {
            if ch.is_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect();
    let name = if name.starts_with(|ch: char| ch.is_ascii_digit()) {
        format!("_{name}")
    } else {
        name
    };
    if SUFFIXED.contains(&name.as_str()) {
        format!("{name}_")
    } else if RESERVED.contains(&name.as_str()) {
        format!("r#{name}")
    } else {
        name
    }
}
