// generated by `sysml rustgen` -- DO NOT EDIT
//
// Definitions of the model become structs and enums; ports bound to
// existing Rust APIs become generic parameters, `perform`ed actions
// methods, and state definitions state machines. What the model
// leaves abstract becomes a trait for you to implement -- alongside
// this file, not in it.

/// SysML: `enum def Urgency`
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Urgency {
    /// SysML: `enum routine`
    Routine,
    /// SysML: `enum rush`
    Rush,
}

impl Default for Urgency {
    fn default() -> Self {
        Urgency::Routine
    }
}

/// SysML: `enum def OrderType`
// not generated: `replenishment` -- only `enum` values become variants
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OrderType {
}

/// One article of a replenishment order.
/// SysML: `part def OrderLine`
#[derive(Debug, Clone, PartialEq)]
pub struct OrderLine {
    pub sku: String,
    pub amount: u64,
    pub batch: u64,
    pub urgency: Urgency,
}

impl Default for OrderLine {
    fn default() -> Self {
        Self {
            sku: Default::default(),
            amount: 1,
            batch: 6 * 4,
            urgency: Default::default(),
        }
    }
}

impl OrderLine {
    /// SysML: `calc bulk`
    pub fn bulk(&self) -> bool {
        self.amount >= self.batch
    }
}

/// Replenish when the level falls below the threshold.
/// SysML: `calc def NeedsRestock`
pub fn needs_restock(level: u64, threshold: u64) -> bool {
    level < threshold
}

/// Plans replenishment against the in-house inventory API.
/// SysML: `part def OrderPlanner`
pub struct OrderPlanner<Store: inventory_store::InventoryStore> {
    /// SysML: `port store : InventoryStore`
    pub store: Store,
    pub threshold: u64,
    pub lines: Vec<OrderLine>,
}

impl<Store: inventory_store::InventoryStore> OrderPlanner<Store> {
    /// SysML: `perform action check : GetStock` -> `inventory_store::InventoryStore::get_stock`
    pub fn check(&self, query: inventory_store::StockQuery) -> Result<inventory_store::StockLevel, inventory_store::StoreError> {
        self.store.get_stock(query)
    }

    /// SysML: `perform action observe : Watch` -> `inventory_store::InventoryStore::watch`
    pub async fn observe(&self, sku: String) -> inventory_store::StockLevel {
        self.store.watch(sku).await
    }

    /// SysML: `perform action reset : Refresh` -> `inventory_store::InventoryStore::refresh`
    pub fn reset(&mut self) {
        self.store.refresh()
    }
}

/// A site running one planner against the shared inventory.
/// SysML: `part def Warehouse`
pub struct Warehouse<PlannerStore: inventory_store::InventoryStore> {
    pub site: String,
    pub planner: OrderPlanner<PlannerStore>,
}

/// How one replenishment round proceeds.
/// SysML: `state def OrderPhase` -- the states
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OrderPhaseState {
    Idle,
    Ordering,
}

impl OrderPhaseState {
    /// The first state the definition declares.
    #[must_use]
    pub fn initial() -> Self {
        OrderPhaseState::Idle
    }
}

/// What `OrderPhaseState::step` reacts to.
pub enum OrderPhaseEvent {
    Submit(OrderLine),
    Settle,
}

/// The machine's open decisions; every hook has a default.
#[allow(unused_variables)]
pub trait OrderPhaseHooks {
    /// SysML guard: `[line.amount > 0]`
    fn guard_submit(&self, line: &OrderLine) -> bool {
        line.amount > 0
    }
    fn on_entry_idle(&mut self) {}
    fn on_exit_idle(&mut self) {}
    fn on_entry_ordering(&mut self) {}
    fn on_exit_ordering(&mut self) {}
}

impl OrderPhaseState {
    /// One step of the machine: the transition table, guards
    /// first, exit-effect-entry in order.
    #[must_use]
    pub fn step(self, event: &OrderPhaseEvent, hooks: &mut impl OrderPhaseHooks) -> Self {
        match (self, event) {
            (OrderPhaseState::Idle, OrderPhaseEvent::Submit(line)) if hooks.guard_submit(line) => {
                hooks.on_exit_idle();
                hooks.on_entry_ordering();
                OrderPhaseState::Ordering
            }
            (OrderPhaseState::Ordering, OrderPhaseEvent::Settle) => {
                hooks.on_exit_ordering();
                hooks.on_entry_idle();
                OrderPhaseState::Idle
            }
            (state, _) => state,
        }
    }
}

/// The model's requirements: one ignored test per requirement,
/// waiting for its verification to be written.
#[cfg(test)]
mod requirements {
    /// SysML: `requirement def StockVisibility`
    /// Every article's stock level must be answerable on demand.
    /// Satisfied by `OrderPlanner`.
    #[test]
    #[ignore = "verification not written yet"]
    fn stock_visibility() {}
}
